// /av-browser-test — exhaustive UI sweep
// Generated by /av skill. Logs in once, walks every (app) route, clicks every
// non-destructive button/link, collects console + network + nav errors,
// writes JSON + Markdown report to docs/04-reports/.

import { test, expect, type Page, type ConsoleMessage } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const BASE_URL = process.env.E2E_BASE_URL ?? "http://localhost:3000";

const ROUTES: string[] = [
  "/home",
  "/workspace",
  "/connections",
  "/schema",
  "/charts",
  "/dashboards",
  "/reports",
  "/saved",
  "/history",
  "/templates",
  "/glossary",
  "/catalog",
  "/schedules",
  "/notifications",
  "/profile",
  "/settings",
  "/ai-context",
  "/ai-providers",
  "/audit-logs",
  "/errors",
  "/admin",
];

const DESTRUCTIVE_RX =
  /(로그아웃|logout|sign out|delete|삭제|drop|reset|초기화|disconnect|연결\s*해제|run|실행|activate|활성화|deactivate|비활성화|publish|배포|create new|새로\s*만들기|invite|초대|remove|제거)/i;

interface RouteResult {
  route: string;
  finalUrl: string;
  status: number | null;
  loadOk: boolean;
  consoleErrors: string[];
  consoleWarnings: string[];
  pageErrors: string[];
  network4xx5xx: { url: string; status: number }[];
  buttons: { total: number; clicked: number; skipped: number; failed: number };
  failures: { label: string; reason: string }[];
  durationMs: number;
}

const results: RouteResult[] = [];

async function attachLogging(page: Page, sink: {
  errs: string[]; warns: string[]; pageErrs: string[]; net: { url: string; status: number }[];
}) {
  page.on("console", (msg: ConsoleMessage) => {
    const t = msg.type();
    const text = `[${t}] ${msg.text()}`;
    if (t === "error") sink.errs.push(text);
    else if (t === "warning") sink.warns.push(text);
  });
  page.on("pageerror", (err) => sink.pageErrs.push(String(err?.message ?? err)));
  page.on("response", (resp) => {
    const s = resp.status();
    if (s >= 400) sink.net.push({ url: resp.url(), status: s });
  });
}

const TEST_EMAIL = process.env.AV_TEST_EMAIL ?? "qatest@vibesql.dev";
const TEST_PASSWORD = process.env.AV_TEST_PASSWORD ?? "qatest123";

async function ensureTestUser() {
  // Best-effort register; ignore conflict
  await fetch(`${BASE_URL}/api/auth/register`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email: TEST_EMAIL, password: TEST_PASSWORD, name: "AV Bot" }),
  }).catch(() => null);
}

async function login(page: Page) {
  await ensureTestUser();
  await page.goto(`${BASE_URL}/signin`, { waitUntil: "networkidle" });
  await page.locator("#signin-email").waitFor({ state: "visible", timeout: 10_000 });
  await page.locator("#signin-email").fill(TEST_EMAIL);
  await page.locator("#signin-password").fill(TEST_PASSWORD);
  const submitBtn = page.locator('form#signin-form button[type="submit"]');
  await Promise.all([
    page.waitForURL((u) => !u.toString().includes("/signin"), { timeout: 20_000 }),
    submitBtn.click(),
  ]);
  await page.waitForLoadState("domcontentloaded");
  if (page.url().includes("/signin")) {
    throw new Error(`login failed: still on ${page.url()}`);
  }
}

test.describe("av-browser-test sweep", () => {
  test.describe.configure({ mode: "serial" });

  test("full menu sweep", async ({ page }) => {
    test.setTimeout(15 * 60_000); // 15 min budget total

    const globalSink = { errs: [], warns: [], pageErrs: [], net: [] as { url: string; status: number }[] };
    await attachLogging(page, globalSink);

    await login(page);

    for (const route of ROUTES) {
      const t0 = Date.now();
      const sink = { errs: [] as string[], warns: [] as string[], pageErrs: [] as string[], net: [] as { url: string; status: number }[] };

      // per-route listeners (fresh)
      const onConsole = (m: ConsoleMessage) => {
        const t = m.type();
        const text = `[${t}] ${m.text()}`;
        if (t === "error") sink.errs.push(text);
        else if (t === "warning") sink.warns.push(text);
      };
      const onPageErr = (e: Error) => sink.pageErrs.push(String(e?.message ?? e));
      const onResp = (r: import("@playwright/test").Response) => {
        const s = r.status();
        if (s >= 400) sink.net.push({ url: r.url(), status: s });
      };
      page.on("console", onConsole);
      page.on("pageerror", onPageErr);
      page.on("response", onResp);

      let resp: import("@playwright/test").Response | null = null;
      let loadOk = false;
      try {
        resp = await page.goto(`${BASE_URL}${route}`, { waitUntil: "domcontentloaded", timeout: 30_000 });
        await page.waitForLoadState("networkidle", { timeout: 8_000 }).catch(() => null);
        // give client components time to hydrate and fetch
        await page.waitForTimeout(1500);
        loadOk = (resp?.status() ?? 0) < 500 && !page.url().includes("/signin");
        if (!loadOk && page.url().includes("/signin")) {
          sink.pageErrs.push(`auth lost: redirected to /signin from ${route}`);
        }
      } catch (e) {
        sink.pageErrs.push(`navigation failed: ${(e as Error).message}`);
      }

      const buttons = { total: 0, clicked: 0, skipped: 0, failed: 0 };
      const failures: { label: string; reason: string }[] = [];

      if (loadOk) {
        // Collect button + link refs in main content (skip top-level shell logout etc by destructive rx)
        const interactive = await page.evaluate(() => {
          const els = Array.from(document.querySelectorAll<HTMLElement>(
            'button:not([disabled]), [role="button"]:not([aria-disabled="true"]), a[href]'
          ));
          return els.map((el, i) => {
            const text = (el.innerText || el.getAttribute("aria-label") || "").trim().slice(0, 80);
            const tag = el.tagName.toLowerCase();
            const href = el.getAttribute("href") ?? "";
            const target = el.getAttribute("target") ?? "";
            const type = (el as HTMLButtonElement).type ?? "";
            const visible = !!(el.offsetParent || el.getClientRects().length);
            // mark with a data attribute so we can resolve later
            el.setAttribute("data-av-idx", String(i));
            return { i, text, tag, href, target, type, visible };
          });
        });

        buttons.total = interactive.length;

        for (const it of interactive) {
          if (!it.visible) { buttons.skipped++; continue; }
          if (DESTRUCTIVE_RX.test(it.text)) { buttons.skipped++; continue; }
          if (it.target === "_blank") { buttons.skipped++; continue; }
          if (/^https?:\/\//i.test(it.href)) { buttons.skipped++; continue; }
          if (it.tag === "button" && it.type === "submit") { buttons.skipped++; continue; }
          // navigation links: count as clicked but don't actually navigate (we'll re-enter via loop)
          if (it.tag === "a") {
            // skip nav links (we visit each route directly anyway)
            buttons.skipped++;
            continue;
          }

          try {
            const loc = page.locator(`[data-av-idx="${it.i}"]`).first();
            // safety: re-check visible & enabled (DOM may have changed after prior click)
            if (!(await loc.isVisible().catch(() => false))) { buttons.skipped++; continue; }
            if (!(await loc.isEnabled().catch(() => false))) { buttons.skipped++; continue; }
            await loc.click({ timeout: 3_000 });
            buttons.clicked++;
            await page.waitForTimeout(200);

            // close any opened dialog/modal
            await page.keyboard.press("Escape").catch(() => null);
            await page.waitForTimeout(100);

            // if URL changed (button caused nav), return to this route and continue loop
            if (!page.url().endsWith(route) && !page.url().includes(`${route}?`) && !page.url().includes(`${route}#`)) {
              await page.goto(`${BASE_URL}${route}`, { waitUntil: "domcontentloaded", timeout: 10_000 }).catch(() => null);
              await page.waitForTimeout(800);
              // DOM changed; stop iterating cached refs (next route will re-enumerate)
              break;
            }
          } catch (e) {
            buttons.failed++;
            failures.push({ label: it.text || `(idx ${it.i})`, reason: (e as Error).message.slice(0, 200) });
          }
        }
      }

      // detach listeners
      page.off("console", onConsole);
      page.off("pageerror", onPageErr);
      page.off("response", onResp);

      results.push({
        route,
        finalUrl: page.url(),
        status: resp?.status() ?? null,
        loadOk,
        consoleErrors: sink.errs,
        consoleWarnings: sink.warns,
        pageErrors: sink.pageErrs,
        network4xx5xx: sink.net,
        buttons,
        failures,
        durationMs: Date.now() - t0,
      });
    }

    // ---- write reports ----
    const outDir = path.resolve(process.cwd(), "docs/04-reports");
    fs.mkdirSync(outDir, { recursive: true });
    const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 16);
    const jsonPath = path.join(outDir, `browser-test-${stamp}.json`);
    const mdPath = path.join(outDir, `browser-test-${stamp}.md`);

    fs.writeFileSync(jsonPath, JSON.stringify({ baseUrl: BASE_URL, results }, null, 2));

    const totals = results.reduce(
      (a, r) => {
        a.routes++;
        if (r.loadOk && r.consoleErrors.length === 0 && r.pageErrors.length === 0) a.pass++;
        else a.fail++;
        a.consoleErr += r.consoleErrors.length;
        a.pageErr += r.pageErrors.length;
        a.net += r.network4xx5xx.length;
        a.btnTotal += r.buttons.total;
        a.btnClicked += r.buttons.clicked;
        a.btnFailed += r.buttons.failed;
        return a;
      },
      { routes: 0, pass: 0, fail: 0, consoleErr: 0, pageErr: 0, net: 0, btnTotal: 0, btnClicked: 0, btnFailed: 0 }
    );

    const md: string[] = [];
    md.push(`# 브라우저 전수 테스트 보고서`);
    md.push("");
    md.push(`- **일시**: ${new Date().toISOString()}`);
    md.push(`- **대상**: ${BASE_URL}`);
    md.push(`- **계정**: admin@vibesql.dev`);
    md.push("");
    md.push(`## Executive Summary`);
    md.push("");
    md.push(`| 항목 | 값 |`);
    md.push(`|---|---|`);
    md.push(`| 라우트 | ${totals.routes} |`);
    md.push(`| 통과 | ${totals.pass} |`);
    md.push(`| 실패 | ${totals.fail} |`);
    md.push(`| 콘솔 에러 | ${totals.consoleErr} |`);
    md.push(`| 페이지 에러 | ${totals.pageErr} |`);
    md.push(`| 4xx/5xx 응답 | ${totals.net} |`);
    md.push(`| 인터랙티브 요소 | ${totals.btnTotal} |`);
    md.push(`| 클릭 성공 | ${totals.btnClicked} |`);
    md.push(`| 클릭 실패 | ${totals.btnFailed} |`);
    md.push("");
    md.push(`## 라우트별 결과`);
    md.push("");
    md.push(`| 라우트 | HTTP | 진입 | 콘솔err | pageErr | 4xx/5xx | 버튼 | 결과 |`);
    md.push(`|---|---|---|---|---|---|---|---|`);
    for (const r of results) {
      const ok = r.loadOk && r.consoleErrors.length === 0 && r.pageErrors.length === 0;
      md.push(
        `| ${r.route} | ${r.status ?? "-"} | ${r.loadOk ? "✅" : "❌"} | ${r.consoleErrors.length} | ${r.pageErrors.length} | ${r.network4xx5xx.length} | ${r.buttons.clicked}/${r.buttons.total} | ${ok ? "✅" : "⚠️"} |`
      );
    }
    md.push("");
    md.push(`## 이슈 상세`);
    md.push("");
    for (const r of results) {
      if (r.consoleErrors.length === 0 && r.pageErrors.length === 0 && r.network4xx5xx.length === 0 && r.failures.length === 0) continue;
      md.push(`### ${r.route}`);
      if (r.consoleErrors.length) {
        md.push(`**Console errors (${r.consoleErrors.length})**:`);
        for (const e of r.consoleErrors.slice(0, 8)) md.push(`- ${e}`);
      }
      if (r.pageErrors.length) {
        md.push(`**Page errors (${r.pageErrors.length})**:`);
        for (const e of r.pageErrors.slice(0, 5)) md.push(`- ${e}`);
      }
      if (r.network4xx5xx.length) {
        md.push(`**Network 4xx/5xx (${r.network4xx5xx.length})**:`);
        for (const n of r.network4xx5xx.slice(0, 8)) md.push(`- ${n.status} ${n.url}`);
      }
      if (r.failures.length) {
        md.push(`**Click failures (${r.failures.length})**:`);
        for (const f of r.failures.slice(0, 5)) md.push(`- "${f.label}" — ${f.reason}`);
      }
      md.push("");
    }

    fs.writeFileSync(mdPath, md.join("\n"));
    console.log(`\n=== AV-BROWSER-SWEEP REPORT ===`);
    console.log(`JSON : ${jsonPath}`);
    console.log(`MD   : ${mdPath}`);
    console.log(`Pass: ${totals.pass}/${totals.routes}  ConsoleErr: ${totals.consoleErr}  Buttons clicked: ${totals.btnClicked}/${totals.btnTotal}`);

    // Soft assertion: don't fail if errors found — we want the report
    expect(totals.routes).toBe(ROUTES.length);
  });
});
